name: Aggregate issues for Instant Issues

on:
  issues:
    types: [opened, closed, reopened, edited, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: instant-issues/action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repos: ${{ github.repository }}
